### ISSUE TITLE
Remember previously entered names

### ISSUE THREAD

**Issue by theRemix** [owen28299/meanRevertingBeuller#7]
use javascript's `localStorage` to remember my student entries between page loads.

if i add 8 students, then refresh, those 8 students should still be entered, and their previous _scores_ should be cleared

difficulty : :star: :star:

**Comment by owen28299** [comment]
DONE! (Although the localStorage function did some funny things I can't explain). I'm guessing it returns arrays that I put in, as strings. So, I ran .split(",") on the output to keep it working.

After entering the names, you can click store to store the value of the students array (as a string, oddly enough).

And you can clear the memory with a clear button (because I couldn't figure out how to actually clear it from Chrome. Clearing cookies and cache didn't work!)

But otherwise, should be working now.
